name: Build Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Clean + Refresh Dependencies
        run: ./gradlew clean --refresh-dependencies

      - name: Build Mod
        run: ./gradlew build --no-daemon --stacktrace

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
